const prisma = require('../config/prisma');
const ApiError = require('../utils/ApiError');

/**
 * Clean Real Pharmacy Integration
 * Connects doctor prescription workflow with pharmacy queue & notifications
 * (No inventory deduction logic executed in Doctor module)
 */
class PharmacyIntegration {
  static async notifyPrescriptionCreated(prescription) {
    try {
      // Find active pharmacist users
      const pharmacists = await prisma.user.findMany({
        where: { role: 'PHARMACIST', isActive: true },
        select: { id: true },
      });

      for (const ph of pharmacists) {
        await prisma.notification.create({
          data: {
            userId: ph.id,
            title: 'New Prescription Queued',
            message: `Dr. Prescription #${prescription.prescriptionNumber} was generated for ${prescription.patient?.fullName || 'Patient'}.`,
            type: 'INFO',
            entityType: 'Prescription',
            entityId: prescription.id,
          },
        });
      }

      return {
        success: true,
        queueToken: `PHARM-TK-${Date.now()}`,
        status: 'QUEUED_FOR_DISPENSING',
      };
    } catch (err) {
      console.warn('Pharmacy integration notification deferred:', err.message);
      return { success: false, error: err.message };
    }
  }
}

class PrescriptionService {
  /**
   * List prescriptions generated by this doctor
   */
  async getPrescriptions(doctorId, query = {}) {
    const { search, status, page = 1, limit = 20 } = query;

    const where = {
      doctorId,
      ...(status && { status }),
    };

    if (search) {
      where.OR = [
        { prescriptionNumber: { contains: search, mode: 'insensitive' } },
        { patient: { fullName: { contains: search, mode: 'insensitive' } } },
        { patient: { patientIdNumber: { contains: search, mode: 'insensitive' } } },
        { items: { some: { medicineName: { contains: search, mode: 'insensitive' } } } },
      ];
    }

    const skip = (parseInt(page, 10) - 1) * parseInt(limit, 10);
    const take = parseInt(limit, 10);

    const [total, prescriptions] = await Promise.all([
      prisma.prescription.count({ where }),
      prisma.prescription.findMany({
        where,
        include: {
          patient: {
            select: {
              id: true,
              patientIdNumber: true,
              fullName: true,
              age: true,
              gender: true,
              phone: true,
              allergies: true,
            },
          },
          items: true,
        },
        orderBy: { prescribedDate: 'desc' },
        skip,
        take,
      }),
    ]);

    return {
      prescriptions,
      pagination: {
        total,
        page: parseInt(page, 10),
        limit: take,
        totalPages: Math.ceil(total / take),
      },
    };
  }

  /**
   * Get single prescription with all medicine items and doctor details
   */
  async getPrescriptionById(doctorId, prescriptionId) {
    const prescription = await prisma.prescription.findFirst({
      where: { id: prescriptionId, doctorId },
      include: {
        patient: true,
        doctor: {
          include: {
            user: {
              select: {
                fullName: true,
                email: true,
                phone: true,
              },
            },
          },
        },
        items: true,
        consultation: {
          select: {
            id: true,
            diagnosis: true,
            chiefComplaint: true,
          },
        },
      },
    });

    if (!prescription) {
      throw ApiError.notFound('Prescription not found');
    }

    return prescription;
  }

  /**
   * Create prescription with multi-item medicines
   */
  async createPrescription(doctorId, data) {
    const { patientId, consultationId, notes, items } = data;

    const patient = await prisma.patient.findUnique({
      where: { id: patientId },
    });

    if (!patient) {
      throw ApiError.notFound('Patient not found');
    }

    // Generate unique prescription number
    const count = await prisma.prescription.count();
    const prescriptionNumber = `RX-2026-${String(count + 101).padStart(3, '0')}`;

    const created = await prisma.prescription.create({
      data: {
        prescriptionNumber,
        doctorId,
        patientId,
        consultationId: consultationId || null,
        notes: notes || null,
        status: 'Active',
        prescribedDate: new Date(),
        items: {
          create: items.map((item) => ({
            medicineName: item.medicineName,
            dosage: item.dosage,
            frequency: item.frequency,
            duration: item.duration,
            route: item.route || 'Oral',
            instructions: item.instructions || null,
          })),
        },
      },
      include: {
        patient: true,
        items: true,
      },
    });

    // Notify Pharmacy stub
    await PharmacyIntegrationStub.notifyPrescriptionCreated(created);

    return created;
  }
}

module.exports = new PrescriptionService();
